version: '3.8'

services:
  freeswitch:
    build:
      context: .
      dockerfile: infrastructure/docker/freeswitch.Dockerfile
    network_mode: "host"
    volumes:
      - ./infrastructure/freeswitch/conf/freeswitch.xml:/usr/local/freeswitch/conf/freeswitch.xml
    depends_on:
      - media-tester

  media-tester:
    build:
      context: .
      dockerfile: infrastructure/docker/media-tester.Dockerfile
    network_mode: "host"
    volumes:
      - ./infrastructure/freeswitch/conf/freeswitch.xml:/app/freeswitch.xml
